apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: flask-check
spec:
  metrics:
    - name: health-check
      interval: 10s
      successCondition: result == 200
      provider:
        web:
          url: http://flask-app/health
          method: GET
