apiVersion: apps/v1                       # Versão da API do Kubernetes usada para Deployment
kind: Deployment                          # Tipo de recurso: Deployment (gerencia pods e ReplicaSets)
metadata:
  name: flask-deployment                  # Nome do Deployment
  labels:
    app: flask-app                        # Label para identificar o recurso

spec:
  replicas: 1                             # Número desejado de réplicas (pods)
  selector:
    matchLabels:
      app: flask-app                      # Seleciona os pods que têm esse label (deve bater com o template)

  template:                               # Template que define os pods criados por esse deployment
    metadata:
      labels:
        app: flask-app                    # Label aplicada aos pods (deve bater com o selector acima)
    spec:
      containers:
        - name: flask                     # Nome do container
          image: vulttur/flask-canary:latest  # Imagem Docker usada para o container
          ports:
            - containerPort: 5000         # Porta exposta pelo container (deve bater com o service)
