apiVersion: v1                     # Versão da API Kubernetes usada para criar o recurso. "v1" é usada para objetos básicos como Service.
kind: Service                      # Tipo de recurso que está sendo criado — aqui é um "Service", que expõe uma aplicação rodando em um ou mais pods.

metadata:                          # Informações descritivas sobre o recurso.
  name: flask-app                  # Nome do Service. Será usado para se referir a esse serviço dentro do cluster (ex: DNS interno).
  labels:                          # Rótulos (labels) para identificar o recurso, geralmente usados para organização ou seleção.
    app: flask-app                 # Label chave:valor. Aqui indica que esse recurso está associado ao app flask-app.

spec:                              # Especificações do comportamento do Service.
  selector:                        # Define para quais pods esse serviço vai encaminhar o tráfego.
    app: flask-app                 # O service irá encaminhar tráfego para pods que tenham esse label (app=flask-app).

  ports:                           # Lista de portas que o serviço vai expor.
    - protocol: TCP                # Protocolo utilizado para a comunicação (TCP nesse caso, padrão para web apps).
      port: 80                     # Porta exposta pelo Service. É a porta que outros recursos vão usar para se comunicar com esse serviço.
      targetPort: 5000            # Porta real que o container/pod escuta. O tráfego recebido na porta 80 será redirecionado para a 5000 no pod.
